package(default_visibility = ["//jdk11/src:__pkg__"])

java_library(
    name = "desugarconfig",
    srcs = glob(["**/*.java"]),
    javacopts = [
        "-source 11",
        "-target 11",
        "-XepAllErrorsAsWarnings",
    ],
)
